### ISSUE TITLE
failed to finalise content install : 0xD8E0806A

### ISSUE THREAD

**Issue by amirusan** [Cruel/freeShop#96] opened 2016-08-22 11:47 UTC
Hi there,

Was told to post this on here. Happens on all titles I've tried so far. After download is complete it says failed to finalise content install : 0xD8E0806A.

Is this a known issue? If you want I can provide screenshots.

Thanks

**Comment by Ninjistix** [comment] 2016-08-22 14:42
think this is related to issue #90

**Comment by Cruel** [comment] 2016-08-22 15:51
No, it's a duplicate of #89

**Closed by Cruel** 2016-08-22 15:51 UTC
Labels: bug, duplicate

**Comment by amirusan** [comment] 2016-08-22 16:29
Oh sorry Cruel, thanks for pointing that out.
