### ISSUE TITLE
FreeShop 2.1.2 fails finalize content at 99,9%

### ISSUE THREAD

**Issue by Antari18** [Cruel/freeShop#168] opened 2016-09-17 10:08 UTC
Yesterday I've downloaded few apps without any problem. Went to sleep. Today it's impossible to download anything. The most frustrating apps are those over 1GB which takes an hour for me to download. 

It's installing normally up to 99%, then when it's nearly finished it said failed to install. I did not change anything on my card from yesterday. Why is this happening?

**Comment by Antari18** [comment] 2016-09-17 10:14
I'm running A9LH O3DS, Luma3DS v6.2.2 on 9.2 sysnand. My SD card have 32 GB. something around 20 GB space left.

**Comment by cheatfreak47** [comment] 2016-09-17 10:17
This is a dupe of #167 
Check the tracker before opening a new issue.

**Comment by Antari18** [comment] 2016-09-17 10:18
No it's not. #167 is a different issue with apps failing at the beginning of instalation. 

I'm going all up to 99%, than when it should be installed it said it failed.

**Comment by cheatfreak47** [comment] 2016-09-17 10:23
So in what world is it a good idea to label two similar issues nearly exactly the same?
Probably would be a good idea to edit the name of the issue to differentiate it.

**Comment by Antari18** [comment] 2016-09-17 11:00
It always said "Fail to finalize content: 0xF9608022

**Comment by Cruel** [comment] 2016-09-17 17:10
I've only seen this issue when there's a problem with the SD card. I would suggest moving your setup to another one and seeing if the problem continues.

**Comment by Antari18** [comment] 2016-09-17 22:45
I bought the card yesterday. It's pretty new and functional. I encountered another problem. I was finally able to download one app and it appeared on home menu. But when I boot the app was still there but it was impossible to open it and it was lacking banner. On data menagement screen it said this app weight is 0.

**Comment by Cruel** [comment] 2016-09-17 23:20
If you can copy a large CIA to your SD card and install it via FBI, I'll believe your SD card is functional. Otherwise still sounds like there's a problem with it.

**Comment by Antari18** [comment] 2016-09-18 08:04
I got already dozen apps downloaded. Some of them via FBI and some of the with freeshop. So I don't think it's the problem with a card. This issue seems very simmilar to #90 but having latest version of freeshop doesn't solve the issue for me. I was able to install few apps yesterday but it seems to fail with larger files like 1,5GB. I downloaded latest encTitleKeys.bin to my card and smaller games like 5MB-200MB start working again. There seem to be issue with larger files like 1-1,8GB etc. I tried installing it through FBI and they also fails.

**Comment by Cruel** [comment] 2016-09-18 17:30
Like I said, if installs are failing with FBI too, it's probably an SD problem like I said.

Just because you already installed stuff doesn't mean there's no SD problem. Depending on where you bought it, for instance, it could easily be fake. Fake cards report a higher capacity to the system, but could just have 16GB capacity rebranded as 64GB. So everything you write to the SD card past 16GB would be ignored and corrupted.

If you're not wanting to try another SD card, try deleting a bigger game and then installing the same size game with freeShop.

Additionally there exists software to test SD cards to make sure they're functioning properly.

**Comment by Antari18** [comment] 2016-09-18 17:42
This also doesn't seem to be the case. After many many tries I was able to download 2 apps today, 800MB each. This would give a total of 1,6GB free space. Yesterday I couldn't download apps over 1GB.

**Comment by moutonnoireu** [comment] 2016-09-18 18:02
Then it's definitely your SD Card who present a problem. Change it.

**Comment by Antari18** [comment] 2016-09-19 11:10
I run diagnostics with my card.

Warning: Only 25715 of 31984 MByte tested.
The media is likely to be defective.
1.0 GByte OK (2243357 sectors)
24.0 GByte DATA LOST (50420963 sectors)
Details:0 KByte overwritten (0 sectors)
0 KByte slightly changed (< 8 bit/sector, 0 sectors)
24.0 GByte corrupted (50420963 sectors)
0 KByte aliased memory (0 sectors)
First error at offset: 0x00000000393d3a00
Expected: 0x00000000393d3a00
Found: 0xb484d7b4583f8688
H2testw version 1.3
Writing speed: 8.67 MByte/s
Reading speed: 13.3 MByte/s
H2testw v1.4

What does this mean? Can I fix this somehow?

**Comment by MostafaMH** [comment] 2016-09-19 12:48
This means you have been scammed. This is a hacked 1gb sd card not a 32gb one.

Return it to the place you bought it from & demand a refund.

**Comment by Antari18** [comment] 2016-09-19 12:55
Yes you're right. I got 7GB of data on the card so I only scanned 25 remaining. It turns out it's hacked 8GB card not 32GB card. I already bought new card (32GB Sandisk Ultra). I also demanded full refund. I hope this one will be good. I'll post about this issue with Freeshop when my card arrives.

**Comment by Antari18** [comment] 2016-09-21 19:54
Ok, so you were right. The card was corrupted. I changed to a new card and everything is downloading and installing just fine. Case closed.

**Closed** 2016-09-22 00:43 UTC
