### ISSUE TITLE
Bug: Preview images of some games are small

### ISSUE THREAD

**Issue by danirpg** [Cruel/freeShop#166] opened 2016-09-16 15:41 UTC
In example: dragon quest wars are have this bug.

![whatsapp image 2016-09-16 at 17 31 41](https://cloud.githubusercontent.com/assets/15187376/18591901/d501004a-7c34-11e6-9105-20bf251db6af.jpeg)

**Comment by Cruel** [comment] 2016-09-16 16:32
Thanks, but this is duplicate of #57

**Closed by Cruel** 2016-09-16 16:32 UTC
Labels: duplicate
