### ISSUE TITLE
Failed to Install Content: 0xD8E08066 Xenoblade

### ISSUE THREAD

**Issue by Kevman323** [Cruel/freeShop#90] opened 2016-08-21 21:27 UTC
When downloading Xenoblade Chronicals, the whole game downloads, then at the end gives this error. This error was fixed in the past. Issue #30 . After that issue was fixed I downloaded Xenoblade fine from the app.  
  
Now It's given this error again on the latest version. I haven't tried downloading a second time yet, since the download takes several hours for me, but not sure what the reason it. I've downloaded several updates and DLC's that worked out fine.   
  
n3DS, a9lh Luma 6.0.1  
  
EDIT: It might be worth noting that I accidentally deleted this game from the games list in freeshop. That's why I'm reinstalling. Not sure if this would cause the issue.

**Comment by Cruel** [comment] 2016-08-21 21:36
Thanks, I'll look into this. Always hard to solve problems like these.

**Comment by Kevman323** [comment] 2016-08-21 21:42
If you can't figure it out, I'll try downloading it again tomorrow to see if it was just an internet hiccup on my end.

**Comment by Cruel** [comment] 2016-08-21 21:47
It probably was an internet hiccup, but it still should be able to handle it fine. Even if you disable wifi in the middle of install it should show a "Waiting for internet..." message and resume normally when it gets internet again. I'm thinking there are some suspend/resume issues that cause this. But I'll let you know if I do anything that I think fixes this.

**Comment by idifahs** [comment] 2016-08-22 00:01
I have the same issue but with Alpha Sapphire. I've tried multiple times on multiple wifi networks so I don't think it's that

**Comment by Ninjistix** [comment] 2016-08-22 00:26
I'm having this problem with Pokemon Y, Alpha Sapphire and Omega Ruby, somehow managed to get X installed... not sure what the issue is.. also Internet speed seems to tank when it enters "sleep mode"

**Comment by kugoyami** [comment] 2016-08-22 01:26
Same problem, but for Mario Kart 7

**Comment by Corey103** [comment] 2016-08-22 01:52
I have the same problem for an update for Super Smash Bros.

**Comment by amirusan** [comment] 2016-08-22 15:00
Yea mine fails on any game.

**Comment by amirusan** [comment] 2016-08-22 15:00
Same reference

**Comment by idifahs** [comment] 2016-08-22 15:05
I don't know if this is what fixed it but I finally got Alpha Sapphire to install after the battery drained fully while leaving freeshop open. I charged it back up and tried again and it worked with no issue

**Comment by Ninjistix** [comment] 2016-08-22 15:07
i forgot to take my charger with me to work, so ill try downloading again tonight with 2.0.2

**Comment by Kevman323** [comment] 2016-08-22 17:49
I started the install again this morning on 2.0.2, and after work, Xenoblade is now installed just fine. No idea what caused the issue the first time, but if others are still having this issue this might actually be something. Not sure.

**Comment by Cruel** [comment] 2016-08-22 17:58
Yeah, I think that further confirms my theory. I think at some point the connection timed out or something similar, and it suspended/resumed the download during install (either once or multiple times). Somewhere in this process, the installation got messed up. I need to reexamine my download code, maybe rewrite it a bit, it's complicated and needs more comments lol: https://github.com/Cruel/freeShop/blob/master/src/DownloadQueue.cpp#L107

**Comment by Cruel** [comment] 2016-08-22 18:57
Wait, are you sure it was 0xD8E09066 and not 0xD8E08066 ? I was reading assuming it was the latter.

**Comment by Kevman323** [comment] 2016-08-22 20:11
I'm not sure what it was before, but I just got what looks like the same error again on a different game, and it's 8066. I probably just made a typo.

**Comment by Kevman323** [comment] 2016-08-22 22:51
Out of 20 games downloading, two gave me this error. Restarted them and so far the first one finished fine. Still downloading the second. So, probably just a download bug.

**Comment by ShaunDreclin** [comment] 2016-08-23 12:56
Oh I didn't know my issue was a duplicate of this one, I searched for the 8066 error code and didn't see anything haha

It's diffifcult for me to test properly because of how long Monster Hunter takes to download on the friend's o3ds, but on my n3ds I've managed to get everything I downloaded just by trying multiple times.

Just to clarify, the error is only happening at like 99.9% completion (not partway through), it looks like it's about to finish and then it says Failed to install 0xD8E08066

**Comment by Ninjistix** [comment] 2016-08-23 14:19
so after i got home from work lastnight, i was able to install 3, 2gb games fine... one error-ed once guess it was my network, but havn't had that error since still on 2.0.2

**Comment by Cruel** [comment] 2016-08-23 16:47
Thanks for reporting. It's a hard bug to duplicate to find the solution to it. But now that I've gotten most of the other bugs fixed in 2.0.3, I'll focus on this one.

**Comment by ShaunDreclin** [comment] 2016-08-23 23:27
unplug your router for a minute? xD

Also after trying several times monster hunter finally downloaded and installed, so yeah this is a very intermittent issue.

**Comment by Cruel** [comment] 2016-08-24 13:34
Shutting down router actually works fine for me, or using my o3ds wifi switch during install. It just has a "Waiting for internet..." message until it's restored.

I connected my 3ds to a proxy running on my laptop that can limit bandwidth and such. Haven't duplicated the problem yet. Worst care scenario is that it does a "Retrying... 1" count up a few times and eventually terminates with "Failed: Internet problems?"

I'll continue to mess with this a little later to hopefully figure it out.

**Comment by 17thspartan** [comment] 2016-08-26 13:54
I've been having issues with both 8066 and 806A. It seems to happen randomly, but it happens far more often than not. The most frustrating thing is that it doesn't happen until the entire download is complete when it hits 100%; and only then will it say that it failed to install content (8066) or failed to finalize content install (806A). If it helps, I've only been trying to install full games, not updates or anything like that.

My default wifi connection can be a bit spotty on my 3ds. I'm not sure why because every other device in my house connects just fine and averages 1mB/s speeds, but the 3ds seems to have highly varying speeds in freeshop on this connection (anywhere from 20kB/s to 800kB/s) despite showing full bars. So I tried it with another wifi network and I'm having the same 8066 and 806A issues.

Other than this error, I have to say the application is easy to use and great overall and I hope you keep up the good work.

http://i.imgur.com/az1bCrJ.jpg

**Comment by Cruel** [comment] 2016-08-26 14:24
Thanks for reporting @17thspartan.

freeShop is supposed to recover properly from internet issues and continue installing when it would otherwise just fail in the middle of the install like CIAngel or FBI. But evidently it's resuming the install improperly and installing improper content which is even worse lol, because it makes you think everything is fine until it's complete.

I have a question, though I don't know if you were paying attention while it was downloading: did any of the download nearly instantly fail after the previous one failed? Or did they all install pretty much to the end?

**Comment by poutros** [comment] 2016-08-26 22:06
Kid Icarus Uprising just gave me this same error. I've had this error with kirby planet robobot but trying a second time solved it.

**Comment by 17thspartan** [comment] 2016-08-27 00:38
I think reordering the downloads, suspending downloads, or in some way making the application start, stop and restart a download is causing the issue, like you suspected.

The second time through downloading that list (from the picture above), I reordered the list, and every download that had some progress, but was stopped by the application when I moved another download to the top, ended up failing with an 8066 error. Any download I let finish without interruption (no reordering of the list, and no exiting the app/resuming the download) didn't have that error and finished just fine.

**Comment by jad340** [comment] 2016-08-27 03:21
Getting the same thing no matter what I try with Super Smash Bros.  It usually gets to around 99.5% before it says "Failed to install Content: 0xD8E08066".

**Closed** 2016-08-27 17:38 UTC
Labels: bug

**Comment by Cruel** [comment] 2016-08-27 17:43
Okay good new, this might be fixed. If you guy could please test 2.0.4 when you can and let me know if this happens still.

**Comment by poutros** [comment] 2016-08-27 17:49
@Cruel No .cia in 2.0.4.

**Comment by jad340** [comment] 2016-08-28 00:12
Seems to work, thank you!
