### ISSUE TITLE
Load local enctitlekeys.bin, hanging/freezing/time-outs on slower connections

### ISSUE THREAD

**Issue by BZ98** [Cruel/freeShop#79] opened 2016-08-21 10:04 UTC
QR and manual-URL attempts to point the program to https://3ds.titlekeys.com/downloadenc both result in a short hang and then the program telling me the request timed out, I assume it's because my connection is massively slow. Loading a bin you already have on your SD card would be nice in the event of network fussiness.

**Comment by idgrepthat** [comment] 2016-08-21 10:25
Have you tried putting the enctitlekeys.bin at /3DS/data/freeShop/keys/download.bin?
Honestly, if your network has issues with a 100K file, I can't imagine the issues it'll have with downloading bulky CDN content...

**Comment by BZ98** [comment] 2016-08-21 10:35
Put enctitlekeys.bin in keys folder before making issue thread, renamed the bin to "download.bin" per your suggestion and no new result.

The actual download of the file isn't an issue because even with my Ethiopia-tier connection it takes only a couple seconds to nab on a computer. It's the program's flat refusal to download anything in the first place because it claims the request timed out that's my problem; I even downloaded it without issue with a third-party enctitlekeys.bin updater cia from a previous release of Freeshop.

**Comment by idgrepthat** [comment] 2016-08-21 10:46
Looks like the iso site is for you then : p

**Comment by BZ98** [comment] 2016-08-21 11:00
Actually it's beginning to look like any system downloads in general for Freeshop 2.0 flatly don't work on slow connections, the program's hung indefinitely while attempting to auto-update from 2.0 to the 2.0.1 hotfix which necessitates a total restart of the system.

**Comment by Cruel** [comment] 2016-08-21 16:39
The problem is that when I remove HTTP timeouts, some issues will cause an indefinite hang when there are connection problems.

I could perhaps allow the timeout value to be customized in settings for people will bad internet.

**Comment by Cruel** [comment] 2016-08-30 07:15
Fixed with b29251b which will be in next release.

**Closed by Cruel** 2016-08-30 07:15 UTC
Labels: bug, enhancement
