### ISSUE TITLE
[Suggestion & Question] Look Inside:

### ISSUE THREAD

**Issue by Hyperom** [Cruel/freeShop#40] opened 2016-06-18 08:19 UTC
**[Suggestion]** Have the 3ds be closed while is downloading, You could Cheat this maybe by just not halving the 3ds go in sleep mode when you close it...Im not sure if thats possible or not...

**[Question]** Why do a bunch of Titles Have a greyed out X? Is this a glitch or is it an issue with the data?

**Comment by deadair3210** [comment] 2016-06-18 14:42
1, As far as I know, with the current tools it is impossible to close the 3DS and keep networking working.

2. If I've been told correctly, and if you are talking about the x's in Data Management, they mean that the ticket for that title is either not installed or corrupted

**Comment by Cruel** [comment] 2016-06-18 16:35
When it's possible to download while in sleep mode, it will be added.

And I believe you're referring to the X indicating that a game doesn't have an icon available. This will be fixed for most games in version 1.2.1 which will probably be released today. But if it still appears, it's not a bug, it just means the icon could not be found.

**Closed by Cruel** 2016-06-18 16:35 UTC
