### ISSUE TITLE
Crashing with intro bgm

### ISSUE THREAD

**Issue by ruvaldak** [Cruel/freeShop#212] opened 2016-11-20 22:31 UTC
When starting the app, if I move the cursor while the added custom intro music is playing before the loop, the app crashes, forcing a hard reset of the 3ds.

**Comment by Cruel** [comment] 2016-11-20 23:30
Duplicate of #193 

I'll make sure this is in next update, hopefully this next week.

**Closed by Cruel** 2016-11-20 23:30 UTC
Labels: bug, duplicate
